import { Geist, Geist_Mono,Cinzel_Decorative, Raleway,Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "./component/Navbar";
import Header from "./component/Header";
import Footer from "./component/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const raleway = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"],
  
});

const cinzel = Cinzel_Decorative({
  variable: "--font-cinzel",
  subsets: ["latin"],
  weight: ['400','700','900']

});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ['400','500','600','700']
  
});

export const metadata = {
  title: "SUM DIM SUM",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${raleway.variable} ${cinzel.variable} antialiased`}
      >
        <Header/>
        
        {children}

        <Footer/>
      </body>
    </html>
  );
}
