import { Geist, Geist_Mono,Cinzel_Decorative, Raleway,Poppins,Open_Sans,Passions_Conflict } from "next/font/google";
import "./globals.css";

import Header from "./component/Header";
import Footer from "./component/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const raleway = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"],
  
});

const cinzel = Cinzel_Decorative({
  variable: "--font-cinzel",
  subsets: ["latin"],
  weight: ['400','700','900']

});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ['400','500','600','700']
  
});

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
  weight: ['400','600','700']
});

const passions_conflict = Passions_Conflict({
  variable: "--font-passions-conflict",
  subsets: ["latin"],
  weight: ['400']
});

export const metadata = {
  title: "SUM DIM SUM",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html className="scroll-smooth" lang="en">
       <head>
        <link
          rel="stylesheet"
          type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.min.css"
        />
        <link
          rel="stylesheet"
          type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick-theme.min.css"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${raleway.variable} ${cinzel.variable} ${poppins.variable} ${openSans.variable} ${passions_conflict.variable} antialiased`}
      >
        <Header/>
        
        {children}

        

        <Footer/>
      </body>
    </html>
  );
}
